"""
Pydantic models for config.json.

Each section of the JSON maps to a model class. Use `Config.model_validate(data)`
to parse and validate a loaded JSON dict. Keys starting with `_` (comments / disabled
entries) are silently ignored by every model via `extra="ignore"`.

Any numeric field accepts a single value or a list for parameter sweeps. Range strings
("start..stop:step") are expanded to lists by load_config before validation reaches here.
"""

from __future__ import annotations
from pathlib import Path
from typing import Union, Optional, Any, Literal
from pydantic import BaseModel, ConfigDict, Field

# Sweepable numeric types. Any field typed with these accepts a single value or a list.
_VNum = Union[float, list[float]]
_VInt = Union[int, list[int]]


def strip_comments(data):
    """Recursively remove keys starting with '_' (comments / disabled entries) from dicts."""
    if isinstance(data, dict):
        return {k: strip_comments(v) for k, v in data.items() if not k.startswith("_")}
    if isinstance(data, list):
        return [strip_comments(item) for item in data]
    return data


class _Base(BaseModel):
    """Base: silently drops unknown keys not defined in the schema."""
    model_config = ConfigDict(extra="ignore")


# =============================================================================
# Environment
# =============================================================================

class EnvironmentConfig(_Base):
    """Launch site environment and atmosphere model configuration.

    Attributes:
        date: 
            Magic string 'tomorrow_08_local' for tomorrow 8 AM, or an explicit local-time
            [year, month, day, hour, min, sec] list.
        latitude: 
            Launch site latitude [°].
        longitude: 
            Launch site longitude [°].
        max_expected_height: 
            Maximum expected height above ground level [m].
        elevation: 
            Launch site elevation above sea level [m].
        timezone: 
            Local launch-site timezone string (e.g. 'Europe/Berlin').
        envType: 
            Atmosphere model type.
            A list requests multiple environments. Do not mix reanalysis types with others.<br>
            Supported values:
            - `standard_atmosphere`: RocketPy standard atmosphere.
            - `Windy`: RocketPy Windy forecast.
            - `custom_atmosphere`: atmosphere loaded from CSV files generated by the weather export script.
            - `reanalysis`: RocketPy reanalysis file.
            - `reanalysis_custom`: custom_atmosphere loaded from existing historical CSV files.
        reanalysis_csv: 
            CSV filenames keyed by model name, used with 'reanalysis_custom'.
        windy_weather_models: 
            Windy weather model name(s), used with 'Windy'.
        custom_weather_models: 
            Custom weather model name(s), used with 'custom_atmosphere'.
        reanalysis_file: 
            Reanalysis data file, used with 'reanalysis'.
        reanalysis_dictionary: 
            Reanalysis dictionary, used with 'reanalysis'.
    """
    date: Union[str, list[int]]
    latitude: _VNum
    longitude: _VNum
    max_expected_height: _VNum
    elevation: _VNum
    timezone: str
    envType: Union[str, list[str]]
    reanalysis_csv: Optional[dict[str, str]] = None
    windy_weather_models: Optional[Union[str, list[str]]] = None
    custom_weather_models: Optional[Union[str, list[str]]] = None
    reanalysis_file: Optional[str] = None
    reanalysis_dictionary: Optional[Any] = None


# =============================================================================
# Engine
# =============================================================================

class EngineConfig(_Base):
    """Motor propulsion type selection.

    Attributes:
        type: 
            Motor propulsion type. Either 'solid' or 'liquid'.
    """
    type: str


class LiquidTankConfig(_Base):
    """Propellant (fuel or oxidizer) tank geometry, flow rate, and fluid properties.

    Attributes:
        length: 
            Tank length [mm].
        outer_diameter: 
            Tank outer diameter [mm].
        volume: 
            Propellant volume [L].
        massflow: 
            Propellant mass flow rate [kg/s].
        position: 
            Tank CG position from the nozzle [mm].
        substance: 
            CoolProp fluid name for this propellant (e.g. 'ethanol', 'oxygen').
        temperature: 
            Propellant temperature [K].
        pressure: 
            Tank pressure [Pa].
    """
    length: _VNum
    outer_diameter: _VNum
    volume: _VNum
    massflow: _VNum
    position: _VNum
    substance: str
    temperature: _VNum
    pressure: _VNum


class PressureGasTankConfig(_Base):
    """Pressurant gas tank. Feeds both the fuel and oxidizer tanks from separate positions.

    Attributes:
        length: 
            Tank length [mm].
        outer_diameter: 
            Tank outer diameter [mm].
        volume: 
            Gas volume [L].
        massflow: 
            Pressurant mass flow rate [kg/s].
        position_fuel: 
            Tank CG position when pressurizing the fuel tank, from nozzle [mm].
        position_oxidizer: 
            Tank CG position when pressurizing the oxidizer tank, from nozzle [mm].
        substance: 
            CoolProp fluid name for the pressurant (e.g. 'N2').
        temperature: 
            Gas temperature [K].
        pressure: 
            Tank pressure [Pa].
    """
    length: _VNum
    outer_diameter: _VNum
    volume: _VNum
    massflow: _VNum
    position_fuel: _VNum
    position_oxidizer: _VNum
    substance: str
    temperature: _VNum
    pressure: _VNum


class LiquidEngineConfig(_Base):
    """Liquid bipropellant motor configuration (pressure-fed, propellant-agnostic).

    Attributes:
        holddown_time: 
            Time the rocket is held down after ignition before release [s].
        nozzle_diameter: 
            Nozzle exit diameter [mm].
        thrust: 
            Thrust curve filename in the project folder (.eng, .rsa, or .csv).
        pressure_gas_tank: 
            Pressurant gas tank configuration.
        fuel_tank: 
            Fuel tank configuration.
        oxidizer_tank: 
            Oxidizer tank configuration.
    """
    holddown_time: _VNum
    nozzle_diameter: _VNum
    thrust: str
    pressure_gas_tank: PressureGasTankConfig
    fuel_tank: LiquidTankConfig
    oxidizer_tank: LiquidTankConfig


# =============================================================================
# Motor
# =============================================================================

class MotorConfig(_Base):
    """Motor physical properties and thrust curve.

    Attributes:
        name: 
            Motor name.
        total_mass: 
            Total (wet) motor mass [g].
        propellant_mass: 
            Propellant mass [g].
        diameter: 
            Motor casing diameter [mm].
        length: 
            Motor casing length [mm].
        burn_time: 
            Nominal burn time [s].
        center_of_dry_mass_factor: 
            Multiplied by motor length to estimate the dry CG
            position from the nozzle.
        thrust: 
            Thrust-curve filename in the project folder (.eng, .rsa, or .csv).
    """
    name: str
    total_mass: _VNum
    propellant_mass: _VNum
    diameter: _VNum
    length: _VNum
    burn_time: _VNum
    center_of_dry_mass_factor: _VNum
    thrust: str


# =============================================================================
# Rocket body
# =============================================================================

class RocketConfig(_Base):
    """Rocket body geometry, mass properties, and drag curves.

    Attributes:
        total_mass_without_motor: 
            Total rocket mass without motor, weighed [g].
        length: 
            Rocket total length, measured [mm].
        total_CG_without_motor_from_tip: 
            Centre of gravity without motor, measured from tip [mm].
        diameter: 
            Rocket body diameter, measured [mm].
        moment_of_intertia_Z: 
            Moment of inertia about the roll (longitudinal) axis, calculated [kg·m²].
        moment_of_intertia_XY: 
            Moment of inertia about the pitch/yaw axes, calculated [kg·m²].
        power_off_drag: 
            Power-off drag coefficient curve filename in the project folder.
        power_on_drag: 
            Power-on drag coefficient curve filename in the project folder.
    """
    total_mass_without_motor: _VNum
    length: _VNum
    total_CG_without_motor_from_tip: _VNum
    diameter: _VNum
    moment_of_intertia_Z: _VNum
    moment_of_intertia_XY: _VNum
    power_off_drag: str
    power_on_drag: str


class NoseconeConfig(_Base):
    """Nosecone geometry.

    Attributes:
        length: 
            Total nosecone length including cylindrical section [mm].
            E.g. aerodynamic (585) + nosetip (74) = 659.
        cylindrical_section_length: 
            Non-aerodynamic cylindrical section length at
            the base of the nosecone [mm].
        kind: 
            RocketPy nosecone shape string (e.g. 'lvhaack').
    """
    length: _VNum
    cylindrical_section_length: _VNum
    kind: str


class RailbuttonsConfig(_Base):
    """Rail button positions measured from the rocket tip.

    Attributes:
        upper_from_tip: 
            Upper rail button position, measured from tip [mm].
        lower_from_tip: 
            Lower rail button position, measured from tip [mm].
    """
    upper_from_tip: _VNum
    lower_from_tip: _VNum


class TailconeConfig(_Base):
    """Tailcone geometry.

    Attributes:
        bottom_radius: 
            Tailcone bottom (rear) radius [mm].
        cylindrical_section_length: 
            Non-aerodynamic cylindrical section length at the top of the tailcone [mm].
        length: 
            Total tailcone length [mm].
    """
    bottom_radius: _VNum
    cylindrical_section_length: _VNum
    length: _VNum


class FinsConfig(_Base):
    """Fin set geometry. Supports freeform (shape_points) or trapezoidal fins.

    Attributes:
        amount: 
            Number of fins.
        position: 
            Distance from the fin root trailing edge to the rocket rear end [mm].
        name: 
            Fin set name / type string.
        shape_points: 
            Freeform fin outline as [(x, y)] points in meters. [0, 0] is
            the root leading edge. The polygon is closed automatically.
        root_chord: 
            Root chord length for trapezoidal fins [mm].
        tip_chord: 
            Tip chord length for trapezoidal fins [mm].
        span: 
            Fin span for trapezoidal fins [mm].
        sweep_length: 
            Sweep length for trapezoidal fins [mm].
    """
    amount: _VInt
    position: _VNum
    name: str
    shape_points: Optional[list[list[float]]] = None
    root_chord: Optional[_VNum] = None
    tip_chord: Optional[_VNum] = None
    span: Optional[_VNum] = None
    sweep_length: Optional[_VNum] = None


# =============================================================================
# Parachutes
# =============================================================================

class ParachuteConfig(_Base):
    """Single parachute deployment and drag configuration.

    Attributes:
        trigger: 
            Deployment trigger: altitude AGL [m] as a float, or the string 'apogee'.
        sampling_rate: 
            Parachute sensor sampling rate [Hz].
        cd_s: 
            Drag area (cd × projected area) [m²]. Provide this or cd + (radius or
            fabric_area).
        cd: 
            Drag coefficient. Combine with radius or fabric_area to derive cd_s.
        radius: 
            Projected parachute radius [m]. Used with cd to compute cd_s.
        fabric_area: 
            Parachute fabric area [m²]. Used with cd to compute cd_s when
            projected area is close to fabric area.
        lag: 
            Deployment lag after trigger [s].
        noise: 
            Pressure sensor noise model as (mean [Pa], std_dev [Pa], time_correlation).
    """
    trigger: Union[_VNum, str]
    sampling_rate: _VNum
    cd_s: Optional[_VNum] = None
    cd: Optional[_VNum] = None
    radius: Optional[_VNum] = None
    fabric_area: Optional[_VNum] = None
    lag: Optional[_VNum] = None
    noise: Optional[tuple] = None


class ParachutesConfig(_Base):
    """All parachutes on the rocket.

    Attributes:
        main: 
            Main (recovery) parachute.
        drogue: 
            Drogue parachute deployed at apogee.
        payload: 
            Payload parachute for a separating payload.
    """
    main: ParachuteConfig
    drogue: Optional[ParachuteConfig] = None
    payload: Optional[ParachuteConfig] = None


# =============================================================================
# Flight
# =============================================================================

class FlightConfig(_Base):
    """Launch rail configuration and sweep parameters.

    Attributes:
        rail_length: 
            Launch rail length [m].
        inclination: 
            Launch rail inclination [°]. 0 = horizontal, 90 = vertical.
            Accepts a single value, a list, or a 'start..stop:step' range string.
        heading: 
            Launch rail heading [°]. 0 = north, 90 = east.
            Accepts a single value, a list, or a 'start..stop:step' range string.
    """
    rail_length: _VNum
    inclination: _VNum
    heading: _VNum


# =============================================================================
# Payload
# =============================================================================

class PayloadConfig(_Base):
    """Deployable payload configuration.

    Attributes:
        mass_total: 
            Total deployable payload mass [g]. Set to 0 when no payload separates.
            A list of values sweeps over multiple payload masses.
        mass: 
            Physical mass of the separated payload body [g]. Required when mass_total > 0.
        diameter: 
            Payload body diameter [mm]. Required when mass_total > 0.
        length: 
            Payload total length [mm]. Required when mass_total > 0.
        moment_of_intertia_XY: 
            Payload moment of inertia about pitch/yaw axes [kg·m²].
        moment_of_intertia_Z: 
            Payload moment of inertia about the roll axis [kg·m²].
    """
    mass_total: _VNum = 0
    mass: Optional[_VNum] = None
    diameter: Optional[_VNum] = None
    length: Optional[_VNum] = None
    moment_of_intertia_XY: Optional[_VNum] = None
    moment_of_intertia_Z: Optional[_VNum] = None


# =============================================================================
# Reanalysis
# =============================================================================

class MotorOverrideConfig(_Base):
    """Per-parameter motor overrides for the matched flight.

    Attributes:
        burn_time: 
            Override burn time [s].
        thrust: 
            Override thrust-curve filename in the project folder.
    """
    burn_time: Optional[_VNum] = None
    thrust: Optional[str] = None            # TODO: implement multiple thrust curves for variation


class ParachuteOverrideConfig(_Base):
    """Per-parameter parachute overrides for the matched flight.

    Attributes:
        enabled: 
            Set to false to remove this parachute from the matched flight entirely.
        cd_s: 
            Override drag area (cd × projected area) [m²].
        cd: 
            Override drag coefficient.
        radius: 
            Override projected radius [m].
        fabric_area: 
            Override fabric area [m²].
    """
    enabled: bool = True
    cd_s: Optional[_VNum] = None
    cd: Optional[_VNum] = None
    radius: Optional[_VNum] = None
    fabric_area: Optional[_VNum] = None


MatchParameter = Literal["heading", "inclination", "velocity"]


class MatchedFlightConfig(_Base):
    """A flight that branches off the nominal at match_time with a sensor-matched initial state.

    Attributes:
        match_time: 
            Time [s] at which to branch off the nominal flight and apply
            sensor-matched attitude/velocity.
        match_parameters: 
            Flight-computer parameters to match at match_time.
            Any subset of: 'heading', 'inclination', 'velocity'.
        motor: 
            Motor overrides applied to the matched flight.
        parachutes: 
            Per-parachute overrides keyed by parachute name (e.g. 'main', 'drogue').
    """
    match_time: Optional[_VNum] = None
    match_parameters: list[MatchParameter] = Field(default_factory=list)
    motor: Optional[MotorOverrideConfig] = None
    parachutes: Optional[dict[str, ParachuteOverrideConfig]] = None


class ReanalysisConfig(_Base):
    """Flight-computer data sources and matched-flight configuration.

    Attributes:
        sources: 
            Flight computers to load data from. Any subset of: 'cats_vega', 'altimax', 'rcu'.
        matched_flight: 
            Configuration for the sensor-matched flight branch. Omit to skip matched-flight simulation.
    """
    sources: list[str]
    matched_flight: Optional[MatchedFlightConfig] = None


# =============================================================================
# Top-level config
# =============================================================================

class Config(_Base):
    """Full project config loaded from config.json.
    
    Attributes:
        project (str): 
            Project name, used for labeling outputs. 
        output_level (int): Controls amount of output generated.
                - `output_level = 0`    (standard): most important prints + landing/safety plots
                - `output_level = 1`    (detailed): level 0 + per-flight custom plots + env prints
                - `output_level = 2`    (more detailed): level 1 + rocket/motor prints
                - `output_level = 3`    (debug): level 2 + more env plots
        environment (EnvironmentConfig): 
            Environment and atmosphere model configuration. Details see EnvironmentConfig.
        engine (EngineConfig): 
            Motor propulsion type selection (solid or liquid). Details see EngineConfig.
        motor (MotorConfig): 
            Solid motor configuration. Required when engine.type is 'solid'. Details see MotorConfig.
        liquid_engine (LiquidEngineConfig): 
            Liquid engine configuration. Required when engine.type is 'liquid'. Details see LiquidEngineConfig.
        rocket (RocketConfig): 
            Rocket body geometry, mass properties, and drag curves. Details see RocketConfig.
        nosecone (NoseconeConfig): 
            Nosecone geometry. Details see NoseconeConfig.
        railbuttons (RailbuttonsConfig): 
            Rail button positions. Details see RailbuttonsConfig.
        tailcone (TailconeConfig): 
            Tailcone geometry. Details see TailconeConfig.
        fins (FinsConfig): 
            Fin set geometry. Details see FinsConfig.
        parachutes (ParachutesConfig): 
            Parachute deployment and drag configuration. Details see ParachutesConfig.
        flight (FlightConfig): 
            Launch rail configuration and sweep parameters. Details see FlightConfig.
        payload (PayloadConfig): 
            Deployable payload configuration. Details see PayloadConfig.
        reanalysis (ReanalysisConfig): 
            Flight-computer data sources and matched-flight configuration for reanalysis mode. Details see ReanalysisConfig.
    """
    project: str
    output_level: int = 0
    environment: EnvironmentConfig
    engine: EngineConfig
    motor: Optional[MotorConfig] = None
    liquid_engine: Optional[LiquidEngineConfig] = None
    rocket: RocketConfig
    nosecone: NoseconeConfig
    railbuttons: RailbuttonsConfig
    tailcone: TailconeConfig
    fins: FinsConfig
    parachutes: ParachutesConfig
    flight: FlightConfig
    payload: PayloadConfig = PayloadConfig()
    reanalysis: Optional[ReanalysisConfig] = None


# =============================================================================
# Runtime and top-level container
# =============================================================================

class RuntimeParams(BaseModel):
    """Runtime objects built incrementally during the simulation pipeline.

    Add new fields here when a create_* function produces an object other code needs.
    All fields are Optional so the object can be created before any simulation runs.

    Attributes:
        environments: 
            Dict of {name: Environment} built by create_environment.
        motor: 
            Motor object built by create_engine.
        nosecone: 
            NoseCone object built by create_rocket.
        tailcone: 
            Tail object built by create_rocket.
        fin_set: 
            Fin set object built by create_rocket.
        parachutes: 
            Dict of {index: Parachute} built by create_rocket.
        rocket: 
            Rocket object built by create_rocket.
        flights_by_env: 
            Dict of {env_name: [scenario_set, ...]} built by create_flight.
        scenario_sets: 
            List of all scenario_set dicts across all environments, built by create_flight.
            Each scenario_set is a ``{scenario_name: Flight}`` dict for one heading/inclination/env combination.<br>
            Keys: 
            - ``"nominal"`` (always)
            - ``"no_main"`` (only with drogue)
            - ``"ballistic"`` (always)
            - ``"matched"`` (only in reanalysis mode)
        ascent_flights_by_env: 
            Dict of {env_name: [Flight, ...]} in scan mode.
        payload_parachute: 
            Payload parachute dict built by deployable_payload.
        payload: 
            Payload rocket dict built by deployable_payload.
        flight_payload: 
            List of payload Flight objects.
        reanalysis_mode: True if any environment is of type reanalysis.
        gnss_3d_traces: 
            Dict of GNSS 3D traces from reanalysis for the trajectory plot.
        flight_computer_impacts: 
            List of flight-computer impact dicts from reanalysis.
        reanalysis_flight_computer_data: 
            Dict of {env_name: loaded flight-computer data}.
        safe_rocket_nominal: 
            Safe nominal rocket flights (safety analysis).
        safe_rocket_no_main: 
            Safe no-main rocket flights (safety analysis).
        safe_rocket_ballistic: 
            Safe ballistic rocket flights (safety analysis).
        safe_rocket_matched: 
            Safe matched rocket flights (safety analysis).
        safe_configurations: 
            List of (env, heading, inclination) tuples classified as safe.
        unsafe_rocket_nominal: 
            Unsafe nominal rocket flights (safety analysis).
        unsafe_rocket_no_main: 
            Unsafe no-main rocket flights (safety analysis).
        unsafe_rocket_ballistic: 
            Unsafe ballistic rocket flights (safety analysis).
        unsafe_rocket_matched: 
            Unsafe matched rocket flights (safety analysis).
        unsafe_configurations: 
            List of (env, heading, inclination) tuples classified as unsafe.
        unsafe_details: 
            List of detail dicts for unsafe configurations.
        safe_payload: 
            Safe payload flights (safety analysis).
        unsafe_payload: 
            Unsafe payload flights (safety analysis).
    """
    model_config = ConfigDict(arbitrary_types_allowed=True)

    environments: Optional[dict] = None
    motor: Optional[Any] = None
    nosecone: Optional[Any] = None
    tailcone: Optional[Any] = None
    fin_set: Optional[Any] = None
    parachutes: Optional[Any] = None
    rocket: Optional[Any] = None
    flights_by_env: Optional[dict] = None
    scenario_sets: list = Field(default_factory=list)
    ascent_flights_by_env: Optional[dict] = None
    payload_parachute: Optional[Any] = None
    payload: Optional[Any] = None
    flight_payload: Optional[list] = None
    reanalysis_mode: bool = False
    gnss_3d_traces: Optional[dict] = None
    flight_computer_impacts: Optional[list] = None
    reanalysis_flight_computer_data: Optional[dict] = None
    safe_rocket_nominal: Optional[list] = None
    safe_rocket_no_main: Optional[list] = None
    safe_rocket_ballistic: Optional[list] = None
    safe_rocket_matched: Optional[list] = None
    safe_configurations: Optional[list] = None
    unsafe_rocket_nominal: Optional[list] = None
    unsafe_rocket_no_main: Optional[list] = None
    unsafe_rocket_ballistic: Optional[list] = None
    unsafe_rocket_matched: Optional[list] = None
    unsafe_configurations: Optional[list] = None
    unsafe_details: Optional[list] = None
    safe_payload: Optional[list] = None
    unsafe_payload: Optional[list] = None


class SimParams(BaseModel):
    """Top-level simulation container: typed config, runtime state, and project metadata.

    Attributes:
        config (Config): 
            Typed configuration loaded from config.json. Use for all parameter access
            instead of flat string-key dicts.
        runtime (RuntimeParams): 
            Runtime objects built during the simulation pipeline. Populated
            incrementally by create_environment, create_engine, create_rocket, etc.
        project_path (Path): 
            Absolute path to the project folder (e.g. ./ALBATROSS/).
        export_kml (bool): 
            True when no flight variations are active (single result → KML export).
    """
    model_config = ConfigDict(arbitrary_types_allowed=True)

    config: Config
    runtime: RuntimeParams = Field(default_factory=RuntimeParams)
    project_path: Path
    export_kml: bool
