"""
RocketPy simulation backend.
"""

import copy
import datetime
from math import pi
from pathlib import Path

import CoolProp.CoolProp as CP
import numpy as np
import pandas as pd

from rocketpy import (
    Environment,
    SolidMotor,
    Rocket,
    Flight,
    Fluid,
    LiquidMotor,
    CylindricalTank,
    MassFlowRateBasedTank,
    TrapezoidalFins,
    FreeFormFins,
    NoseCone,
    Tail,
    Parachute,
    Function,
)

from simulation.utils import *
from simulation.export_weather_data import export_weather_data
from simulation.outputs import *
from simulation.custom_print_and_plot_functions import *
from simulation import deployable_payload

DEBUG = False


# =============================================================================
# Small conversion helpers
# =============================================================================

def millimeters_to_meters(value):
    """
    Convert a value from millimeters to meters.
    """
    return value / 1000


def grams_to_kilograms(value):
    """
    Convert a value from grams to kilograms.
    """
    return value / 1000


def get_position_from_tip(value_from_tip_mm, rocket_length_m):
    """
    Convert a nose-tip-origin position to RocketPy's bottom-origin coordinate system.
    """
    return rocket_length_m - millimeters_to_meters(value_from_tip_mm)


# =============================================================================
# Environment
# =============================================================================

def create_environment(constants, variations, OUTPUT_LEVEL=0):
    """
    Create all configured RocketPy environments.

    Supported values in `environment_envType` are:
    - standard_atmosphere: RocketPy standard atmosphere.
    - Windy: RocketPy Windy forecast.
    - custom_atmosphere: atmosphere loaded from CSV files generated by the weather export script.
    - reanalysis: RocketPy reanalysis file.
    - reanalysis_custom: custom_atmosphere loaded from existing historical CSV files.
    """
    print("Creating environment...")

    parameter_env = []
    # REMARK: defaults might create errors, rather deactivate
    # defaults = {
    #     "envType": "Forecast",
    #     "latitude": 39.232465,
    #     "longitude": -8.172108,
    #     "timezone": "Europe/Rome",
    #     "max_expected_height": 9000,
    #     "elevation": "Open-Elevation",
    #     "date": (datetime.datetime.now() + datetime.timedelta(days=1)),
    # }
    # add_defaults(parameter_env, defaults, constants, variations, "environment")
    fill_parameters(parameter_env, "environment_", constants, variations)
    check_required(
        parameter_env,
        [
            "envType",
            "date",
            "latitude",
            "longitude",
            "max_expected_height",
            "elevation",
            "timezone",
        ],
        "environment",
    )

    # Accumulate every created environment across all combinations, keyed by env.name.
    environments = {}

    for env_values in generate_combinations(parameter_env, constants, variations):
        environment_types = ensure_list(env_values["environment_envType"])

        reanalysis_types = {"reanalysis", "reanalysis_custom"}

        if reanalysis_types.intersection(environment_types) and len(environment_types) > 1:
            raise ValueError("environment_envType 'reanalysis' and 'reanalysis_custom' must be selected alone.")

        latitude = env_values["environment_latitude"]
        longitude = env_values["environment_longitude"]
        timezone = env_values["environment_timezone"]
        elevation = env_values["environment_elevation"]
        max_expected_height_agl = env_values["environment_max_expected_height"]
        max_expected_height_asl = max_expected_height_agl + elevation
        date = env_values["environment_date"]

        if date == "tomorrow_08_local":
            tomorrow = datetime.date.today() + datetime.timedelta(days=1)
            date = (tomorrow.year, tomorrow.month, tomorrow.day, 8, 0, 0)

        if len(date) == 4:
            date = (date[0], date[1], date[2], date[3], 0, 0)

        if "standard_atmosphere" in environment_types:
            standard_env = Environment(max_expected_height=max_expected_height_asl)
            standard_env.set_location(latitude=latitude, longitude=longitude)
            standard_env.set_elevation(elevation)
            # standard_environment.set_elevation("Open-Elevation")         # API currently not working
            standard_env.set_date(date, timezone=timezone)
            standard_env.set_atmospheric_model(type="standard_atmosphere")
            standard_env.name = "Standardized"
            attach_meta(standard_env, {key: env_values[key] for key in variations if key in env_values})
            environments[standard_env.name] = standard_env

        if "Windy" in environment_types:
            require_value(env_values, "environment_windy_weather_models", "Windy environment")

            for weather_model in ensure_list(env_values["environment_windy_weather_models"]):
                forecast_env = Environment(max_expected_height=max_expected_height_asl)
                forecast_env.set_location(latitude=latitude, longitude=longitude)
                forecast_env.set_elevation(elevation)
                # forecast_environment.set_elevation("Open-Elevation")         # API currently not working
                forecast_env.set_date(date, timezone=timezone)
                forecast_env.set_atmospheric_model(type="Windy", file=weather_model)
                forecast_env.name = f"{weather_model}_WINDY"
                attach_meta(forecast_env, {key: env_values[key] for key in variations if key in env_values})
                environments[forecast_env.name] = forecast_env

        if "custom_atmosphere" in environment_types:
            require_value(env_values, "environment_custom_weather_models", "custom atmosphere environment")
            project_path = Path(constants["project"])
            output_folder = project_path / "weather_csvs"
            launch_time = datetime.datetime(*date).strftime("%Y-%m-%dT%H:%M:%S")

            for weather_model in ensure_list(env_values["environment_custom_weather_models"]):
                print(f"\nCreating weather CSV files for {weather_model}...")
                export_weather_data(
                    latitude=latitude,
                    longitude=longitude,
                    max_expected_height_agl_m=max_expected_height_agl,
                    launch_time=launch_time,
                    timezone=timezone,
                    weather_model=weather_model,
                    output_folder=output_folder,
                )
                
                # # Load the .csv file into the environment 
                # https://docs.rocketpy.org/en/latest/user/environment/3-further/data_csv.html#load-the-csv-file
                csv_path = output_folder / f"rocketpy_atmosphere_{weather_model}.csv"

                if not csv_path.exists():
                    raise FileNotFoundError(f"Custom environment CSV was not created: {csv_path}")

                dataframe = pd.read_csv(csv_path)
                
                # Create Function objects to represent the profiles
                pressure_function = Function(np.column_stack([dataframe["height"], dataframe["pressure"]]))
                temperature_function = Function(np.column_stack([dataframe["height"], dataframe["temperature"]]))
                wind_u_function = Function(np.column_stack([dataframe["height"], dataframe["wind_u"]]))
                wind_v_function = Function(np.column_stack([dataframe["height"], dataframe["wind_v"]]))

                custom_env= Environment(max_expected_height=max_expected_height_asl)
                custom_env.set_location(latitude=latitude, longitude=longitude)
                custom_env.set_elevation(elevation)
                custom_env.set_date(date, timezone=timezone)
                custom_env.set_atmospheric_model(
                    type="custom_atmosphere",
                    pressure=pressure_function,
                    temperature=temperature_function,
                    wind_u=wind_u_function,
                    wind_v=wind_v_function,
                )
                custom_env.name = f"Custom_{weather_model}"
                attach_meta(custom_env, {key: env_values[key] for key in variations if key in env_values})
                environments[custom_env.name] = custom_env

        if "reanalysis" in environment_types:
            require_value(env_values, "environment_reanalysis_file", "reanalysis environment")
            require_value(env_values, "environment_reanalysis_dictionary", "reanalysis environment")
            reanalysis_file = env_values["environment_reanalysis_file"]
            reanalysis_dictionary = env_values["environment_reanalysis_dictionary"]

            reanalysis_env = Environment(max_expected_height=max_expected_height_asl)
            reanalysis_env.set_location(latitude=latitude, longitude=longitude)
            reanalysis_env.set_elevation(elevation)
            reanalysis_env.set_date(date, timezone=timezone)
            reanalysis_env.set_atmospheric_model(
                type="Reanalysis",
                file=get_project_file(constants, reanalysis_file),
                dictionary=reanalysis_dictionary,
            )
            reanalysis_env.name = f"Reanalysis_{Path(reanalysis_file).stem}"
            attach_meta(reanalysis_env, {key: env_values[key] for key in variations if key in env_values})
            environments[reanalysis_env.name] = reanalysis_env

        if "reanalysis_custom" in environment_types:
            csv_prefix = "environment_reanalysis_csv_"
            reanalysis_csv = {key[len(csv_prefix):]: env_values[key] for key in env_values if key.startswith(csv_prefix)}

            if not reanalysis_csv:
                raise KeyError("Missing required config key for reanalysis environment: reanalysis_csv")

            for model_name, csv_file in reanalysis_csv.items():
                project_path = Path(constants["project"])
                csv_path = Path(csv_file)

                if not csv_path.exists():
                    csv_path = project_path / csv_file

                if not csv_path.exists():
                    csv_path = project_path / "weather_csvs" / csv_file

                if not csv_path.exists():
                    raise FileNotFoundError(f"Reanalysis CSV file not found: {csv_file}")

                dataframe = pd.read_csv(csv_path)
                pressure_function = Function(np.column_stack([dataframe["height"], dataframe["pressure"]]))
                temperature_function = Function(np.column_stack([dataframe["height"], dataframe["temperature"]]))
                wind_u_function = Function(np.column_stack([dataframe["height"], dataframe["wind_u"]]))
                wind_v_function = Function(np.column_stack([dataframe["height"], dataframe["wind_v"]]))

                reanalysis_env = Environment(max_expected_height=max_expected_height_asl)
                reanalysis_env.set_location(latitude=latitude, longitude=longitude)
                reanalysis_env.set_elevation(elevation)
                reanalysis_env.set_date(date, timezone=timezone)
                reanalysis_env.set_atmospheric_model(
                    type="custom_atmosphere",
                    pressure=pressure_function,
                    temperature=temperature_function,
                    wind_u=wind_u_function,
                    wind_v=wind_v_function,
                )
                reanalysis_env.name = f"Reanalysis_Custom_{model_name}"
                attach_meta(reanalysis_env, {key: env_values[key] for key in variations if key in env_values})
                environments[reanalysis_env.name] = reanalysis_env

    if OUTPUT_LEVEL > 1:
        for name, env in environments.items():
            print_one_environment(env, name)
            plot_wind_speed_and_heading(env, max_expected_height_asl)
        if OUTPUT_LEVEL > 2:
            env.plots.atmospheric_model()
            
    constants, variations = register("environments", environments, constants, variations)

    return constants, variations


# =============================================================================
# Engine
# =============================================================================
def create_engine(constants, variations, OUTPUT_LEVEL):
    """
    Create the configured motor type.
    """
    print("Creating engine...")

    parameter_engine = []
    fill_parameters(parameter_engine, "engine_", constants, variations)
    check_required(parameter_engine, {"type"}, "engine")

    engine_type = lookup("engine_type", constants, variations)[0]

    if engine_type == "liquid":
        return create_liquid_engine(constants, variations, OUTPUT_LEVEL)

    if engine_type == "solid":
        return create_solid_engine(constants, variations, OUTPUT_LEVEL)

    raise ValueError(f"Unknown engine_type '{engine_type}'. Use 'solid' or 'liquid'.")


def create_liquid_engine(constants, variations, OUTPUT_LEVEL):
    """
    Create liquid motors from tank and mass-flow configuration.
    """
    print("Creating liquid engine...")

    # TODO: use fuel instead of "ethanol"
    parameter_motor = []
    fill_parameters_exact(parameter_motor, ["holddown_time", "nozzle_diameter", "thrust"], constants, variations)
    fill_parameters(parameter_motor, "nitrogen_tank_", constants, variations)
    fill_parameters(parameter_motor, "ethanol_tank_", constants, variations)
    fill_parameters(parameter_motor, "lox_tank_", constants, variations)
    fill_parameters(parameter_motor, "pressure_", constants, variations)
    fill_parameters(parameter_motor, "temperature_", constants, variations)

    check_required(parameter_motor, ["holddown_time", "nozzle_diameter", "thrust"])
    check_required(parameter_motor, ["length", "outer_diameter", "volume", "massflow"], "nitrogen_tank")
    check_required(parameter_motor, ["length", "outer_diameter", "volume", "massflow"], "ethanol_tank")
    check_required(parameter_motor, ["length", "outer_diameter", "volume", "massflow"], "lox_tank")
    check_required(parameter_motor, ["nitrogen_tank_CG_ethanol", "nitrogen_tank_CG_lox"])
    check_required(parameter_motor, ["temperature_nitrogen", "temperature_ethanol", "temperature_lox"])
    check_required(parameter_motor, ["pressure_nitrogen", "pressure_ethanol", "pressure_lox"])
    
    # defaults = {
    #     "temperature_nitrogen": 298.15,                # K       # preset (= 25°C)
    #     "temperature_ethanol": 298.15,                # K       # preset (= 25°C)
    #     "temperature_lox": 93.15,                    # K       # preset (= -180°C)
    #     "pressure_nitrogen": 30000000,              # Pa     # preset
    #     "pressure_ethanol": 3000000,              # Pa     # preset
    #     "pressure_lox": 3000000,             # Pa     # preset
    # }
    # add_defaults(parameter_motor, defaults, constants, variations)
    
    if DEBUG: 
        print(parameter_motor)
        
    motors = []

    # TODO: use "pressure_gas" instead of nitrogen
    for motor_values in generate_combinations(parameter_motor, constants, variations):
        # Propellants

        # define density
        rho_nitrogen = CP.PropsSI("D", "T", motor_values["temperature_nitrogen"], "P|gas", motor_values["pressure_nitrogen"], "N2")        # kg/m^3
        rho_ethanol = CP.PropsSI("D", "T|liquid", motor_values["temperature_ethanol"], "P", motor_values["pressure_ethanol"], "ethanol")   # kg/m^3
        rho_lox = CP.PropsSI("D", "T|liquid", motor_values["temperature_lox"], "P", motor_values["pressure_lox"], "oxygen")                # kg/m^3

        # define fluids
        nitrogen = Fluid(name="N2", density=rho_nitrogen)
        ethanol = Fluid(name="ethanol", density=rho_ethanol)
        lox = Fluid(name="LOX", density=rho_lox)

        # define tanks geometry
        nitrogen_tank_shape = CylindricalTank(
            radius=millimeters_to_meters(motor_values["nitrogen_tank_outer_diameter"]) / 2,
            height=millimeters_to_meters(motor_values["nitrogen_tank_length"]),
            spherical_caps=True,
        )
        ethanol_tank_shape = CylindricalTank(
            radius=millimeters_to_meters(motor_values["ethanol_tank_outer_diameter"]) / 2,
            height=millimeters_to_meters(motor_values["ethanol_tank_length"]),
            spherical_caps=True,
        )
        lox_tank_shape = CylindricalTank(
            radius=millimeters_to_meters(motor_values["lox_tank_outer_diameter"]) / 2,
            height=millimeters_to_meters(motor_values["lox_tank_length"]),
            spherical_caps=True,
        )

        mass_nitrogen = motor_values["nitrogen_tank_volume"] / 1000 * rho_nitrogen          # m
        mass_ethanol = motor_values["ethanol_tank_volume"] / 1000 * rho_ethanol             # m
        mass_lox = motor_values["lox_tank_volume"] / 1000 * rho_lox                         # m

        burn_time_ethanol = mass_ethanol / motor_values["ethanol_tank_massflow"]            # s
        burn_time_lox = mass_lox / motor_values["lox_tank_massflow"]
        # account for holddown
        burn_time = min(burn_time_ethanol, burn_time_lox) - motor_values["holddown_time"]

        mass_nitrogen = motor_values["nitrogen_tank_massflow"] * burn_time + 0.0001
        mass_ethanol = motor_values["ethanol_tank_massflow"] * burn_time + 0.0001
        mass_lox = motor_values["lox_tank_massflow"] * burn_time + 0.0001

        # define tanks
        nitrogen_tank = MassFlowRateBasedTank(
            name="nitrogen tank",
            geometry=nitrogen_tank_shape,
            flux_time=burn_time,                              # s
            initial_liquid_mass=0,                            # kg
            initial_gas_mass=mass_nitrogen,                   # kg
            liquid_mass_flow_rate_in=0,                       # kg/s
            liquid_mass_flow_rate_out=0,                      # kg/s
            gas_mass_flow_rate_in=0,                          # kg/s
            gas_mass_flow_rate_out=lambda t: motor_values["nitrogen_tank_massflow"],   # ks/s
            liquid=Fluid(name="liquid", density=0.0001),  # ignore
            gas=nitrogen,
        )
        ethanol_tank = MassFlowRateBasedTank(
            name="fuel tank",
            geometry=ethanol_tank_shape,
            flux_time=burn_time,                                 # s
            initial_liquid_mass=mass_ethanol,                    # kg
            initial_gas_mass=0,                                 # kg
            liquid_mass_flow_rate_in=0,                         # kg/s
            liquid_mass_flow_rate_out=lambda t: motor_values["ethanol_tank_massflow"], # kg/s
            gas_mass_flow_rate_in=lambda t: motor_values["nitrogen_tank_massflow"],    # kg/s
            gas_mass_flow_rate_out=0,                         # kg/s
            liquid=ethanol,
            gas=nitrogen,
        )
        lox_tank = MassFlowRateBasedTank(
            name="oxidizer tank",
            geometry=lox_tank_shape,
            flux_time=burn_time,                                    # s
            initial_liquid_mass=mass_lox,                           # kg
            initial_gas_mass=0,                                     # kg
            liquid_mass_flow_rate_in=0,                             # kg/s
            liquid_mass_flow_rate_out=lambda t: motor_values["lox_tank_massflow"],      # kg/s
            gas_mass_flow_rate_in=lambda t: motor_values["nitrogen_tank_massflow"],     # kg/s
            gas_mass_flow_rate_out=0,                               # kg/s
            liquid=lox,
            gas=nitrogen,
        )

        if DEBUG: 
            print(motor_values["thrust"])
            
        motor = LiquidMotor(
            dry_mass=0.0001,                        # kg
            dry_inertia=(0, 0, 0),                  # kg*m^2
            center_of_dry_mass_position=0,          # m
            nozzle_radius=millimeters_to_meters(motor_values["nozzle_diameter"]) / 2, # m
            nozzle_position=0,  # m
            thrust_source=get_project_file(constants, motor_values["thrust"]),   # N
            burn_time=burn_time,                 # s
            coordinate_system_orientation="nozzle_to_combustion_chamber",
        )
        motor.add_tank(tank=nitrogen_tank, position=millimeters_to_meters(motor_values["nitrogen_tank_CG_ethanol"]))
        motor.add_tank(tank=nitrogen_tank, position=millimeters_to_meters(motor_values["nitrogen_tank_CG_lox"]))
        motor.add_tank(tank=ethanol_tank, position=millimeters_to_meters(motor_values["ethanol_tank_CG"]))
        motor.add_tank(tank=lox_tank, position=millimeters_to_meters(motor_values["lox_tank_CG"]))

        attach_meta(motor, {key: motor_values[key] for key in variations if key in motor_values})
        motors.append(motor)
        
        if OUTPUT_LEVEL > 1:
            print_one_motor(motor, type="liquid")
            plot_one_motor(motor)
        
    return register("motor", motors, constants, variations)


def create_solid_engine(constants, variations, OUTPUT_LEVEL):
    """
    Create solid motors from the config.
    """
    print("Creating solid engine...")

    parameter_motor = []
    fill_parameters(parameter_motor, "motor_", constants, variations)
    # defaults = {
    #     "motor_coordinate_system_orientation": "nozzle_to_combustion_chamber",
    #     "motor_dry_inertia": (0.1, 0.1, 0.001),
    #     "holddown_time": 0,
    # }
    # add_defaults(parameter_motor, defaults, constants, variations)
    check_required(
        parameter_motor,
        [
            "name",
            "total_mass",
            "propellant_mass",
            "diameter",
            "length",
            "burn_time",
            "center_of_dry_mass_factor",
            "thrust",
        ],
        "motor",
    )
    
    if DEBUG: 
        print(parameter_motor)

    motors = []

    for motor_values in generate_combinations(parameter_motor, constants, variations):
        motor_total_mass = grams_to_kilograms(motor_values["motor_total_mass"])
        motor_propellant_mass = grams_to_kilograms(motor_values["motor_propellant_mass"])
        motor_dry_mass = motor_total_mass - motor_propellant_mass
        motor_radius = millimeters_to_meters(motor_values["motor_diameter"]) / 2
        motor_length = millimeters_to_meters(motor_values["motor_length"])
        motor_volume = pi * motor_radius**2 * motor_length                                                  # m³
        motor_grain_density = motor_propellant_mass / motor_volume                                          # kg/m³
        
        # inertia of motor without propellant (dry mass) using formula for thin cylindrical shell with open ends
        dry_inertia_x_y = 1 / 12 * motor_dry_mass * (6 * motor_radius**2 + motor_length**2)                 # kg*m²
        dry_inertia_z = motor_dry_mass * motor_radius**2                                                    # kg*m²

        motor = SolidMotor(
            thrust_source=get_project_file(constants, motor_values["motor_thrust"]),
            dry_mass=motor_dry_mass,
            dry_inertia=(dry_inertia_x_y, dry_inertia_x_y, dry_inertia_z),                                  # kg*m²
            nozzle_radius=motor_radius,
            grain_number=1,
            grain_density=motor_grain_density,
            grain_outer_radius=motor_radius,
            grain_initial_inner_radius=0,
            grain_initial_height=motor_length,
            grain_separation=0,
            grains_center_of_mass_position=motor_length / 2,
            center_of_dry_mass_position=motor_length * motor_values["motor_center_of_dry_mass_factor"],
            nozzle_position=0,
            burn_time=motor_values["motor_burn_time"],
            throat_radius=motor_radius / 2,
            coordinate_system_orientation="nozzle_to_combustion_chamber",
        )

        attach_meta(motor, {key: motor_values[key] for key in variations if key in motor_values})
        motors.append(motor)

        if OUTPUT_LEVEL > 1:
            print_one_motor(motor, type="solid", inertia=(dry_inertia_x_y, dry_inertia_z))
            plot_one_motor(motor)
        
    return register("motor", motors, constants, variations)


# =============================================================================
# Rocket parts
# =============================================================================

def create_nosecone(constants, variations):
    """
    Create nosecone objects from config.
    """
    print("Creating nosecone...")

    parameter_nosecone = []
    # defaults = {"nosecone_kind": "von karman"}
    # add_defaults(parameter_nosecone, defaults, constants, variations)
    
    fill_parameters_exact(parameter_nosecone, "rocket_diameter", constants, variations)
    fill_parameters(parameter_nosecone, "nosecone_", constants, variations)
    check_required(parameter_nosecone, ["diameter"], "rocket")
    check_required(parameter_nosecone, ["length", "cylindrical_section_length", "kind"], "nosecone")
    
    if DEBUG: 
        print(parameter_nosecone)
    
    nosecones = []

    for nosecone_values in generate_combinations(parameter_nosecone, constants, variations):
        aerodynamic_length = nosecone_values["nosecone_length"] - nosecone_values["nosecone_cylindrical_section_length"]
        nosecone = NoseCone(
            length=millimeters_to_meters(aerodynamic_length),
            base_radius=millimeters_to_meters(nosecone_values["rocket_diameter"]) / 2,
            kind=nosecone_values["nosecone_kind"],
        )
        attach_meta(nosecone, {key: nosecone_values[key] for key in variations if key in nosecone_values})
        nosecones.append(nosecone)

    return register("nosecone", nosecones, constants, variations)


def create_tailcone(constants, variations):
    """
    Create tailcone objects from config.
    """
    print("Creating tailcone...")

    parameter_tailcone = []

    # defaults = {"tailcone_cylindrical_section_length": 0}
    # add_defaults(parameter_tailcone, defaults, constants, variations)
    fill_parameters(parameter_tailcone, "tailcone_", constants, variations)
    fill_parameters_exact(parameter_tailcone, "rocket_diameter", constants, variations)
    check_required(parameter_tailcone, ["diameter"], "rocket")
    check_required(parameter_tailcone, ["bottom_radius", "cylindrical_section_length", "length"], "tailcone")

    if DEBUG:
        print(parameter_tailcone)

    tailcones = []

    for tailcone_values in generate_combinations(parameter_tailcone, constants, variations):
        aerodynamic_length = tailcone_values["tailcone_length"] - tailcone_values["tailcone_cylindrical_section_length"]
        tailcone = Tail(
            top_radius=millimeters_to_meters(tailcone_values["rocket_diameter"]) / 2,
            bottom_radius=millimeters_to_meters(tailcone_values["tailcone_bottom_radius"]),
            length=millimeters_to_meters(aerodynamic_length),
            rocket_radius=millimeters_to_meters(tailcone_values["rocket_diameter"]) / 2,
        )
        attach_meta(tailcone, {key: tailcone_values[key] for key in variations if key in tailcone_values})
        tailcones.append(tailcone)

    return register("tailcone", tailcones, constants, variations)


def create_fins(constants, variations, OUTPUT_LEVEL):
    """
    Create either freeform or trapezoidal fin sets.
    """
    print("Creating fins...")

    parameter_fins = []

    # defaults = {"fins_amount": 4, "fins_name": "fins"}
    # add_defaults(parameter_fins, defaults, constants, variations)
    fill_parameters(parameter_fins, "fins_", constants, variations)
    fill_parameters_exact(parameter_fins, ["rocket_diameter", "tailcone_bottom_radius"], constants, variations)
    check_required(parameter_fins, ["amount", "name", "position"], "fins")
    check_required(parameter_fins, ["diameter"], "rocket")
    check_required(parameter_fins, ["bottom_radius"], "tailcone")

    if "fins_shape_points" not in parameter_fins:
        check_required(parameter_fins, ["root_chord", "tip_chord", "span", "sweep_length"], "fins")

    fin_sets = []

    for fin_values in generate_combinations(parameter_fins, constants, variations):
        if "fins_shape_points" in fin_values:
            fin_set = FreeFormFins(
                n=fin_values["fins_amount"],
                shape_points=fin_values["fins_shape_points"],                                       # m
                rocket_radius=millimeters_to_meters(fin_values["tailcone_bottom_radius"]),          # m
                name=fin_values["fins_name"],
            )
        else:
            fin_set = TrapezoidalFins(
                n=fin_values["fins_amount"],
                root_chord=millimeters_to_meters(fin_values["fins_root_chord"]),                    # m
                tip_chord=millimeters_to_meters(fin_values["fins_tip_chord"]),                      # m
                span=millimeters_to_meters(fin_values["fins_span"]),                                # m
                sweep_length=millimeters_to_meters(fin_values["fins_sweep_length"]),                # m
                name=fin_values["fins_name"],
                rocket_radius=millimeters_to_meters(fin_values["rocket_diameter"]) / 2,             # m
            )

        attach_meta(fin_set, {key: fin_values[key] for key in variations if key in fin_values})
        fin_sets.append(fin_set)
        
        if OUTPUT_LEVEL > 1:
            print_one_fin_set(fin_set)
            fin_set.draw()

    return register("fin_set", fin_sets, constants, variations)


def get_parachute_cd_s(parachute_values, prefix):
    """
    Return `cd_s` directly or compute it from drag coefficient and area inputs.
    """
    cd_s_key = f"{prefix}_cd_s"
    cd_key = f"{prefix}_cd"
    radius_key = f"{prefix}_radius"
    fabric_area_key = f"{prefix}_fabric_area"

    if cd_s_key in parachute_values:
        return parachute_values[cd_s_key]

    if cd_key in parachute_values and fabric_area_key in parachute_values:
        return parachute_values[cd_key] * parachute_values[fabric_area_key]

    if cd_key in parachute_values and radius_key in parachute_values:
        return parachute_values[cd_key] * pi * parachute_values[radius_key] ** 2

    raise ValueError(f"Parachute '{prefix}' needs either cd_s, cd + radius, or cd + fabric_area.")


def create_parachutes(constants, variations, OUTPUT_LEVEL):
    """
    Create main and optional drogue parachutes.
    """
    print("Creating parachutes...")

    has_drogue = any(key.startswith("parachutes_drogue_") for key in list(constants) + list(variations))
    parameter_parachutes = []

    # defaults = {
    #     "parachutes_main_sampling_rate": 100,          # hz              # preset
    #     "parachutes_main_lag": 4,                       # s               # measured
    # }
    # if has_drogue:
    #     defaults.update({
    #         "parachutes_drogue_sampling_rate": 100,
    #         "parachutes_drogue_lag": 1,
    #     })
    # add_defaults(parameter_parachutes, defaults, constants, variations)

    fill_parameters(parameter_parachutes, "parachutes_main_", constants, variations)

    if has_drogue:
        fill_parameters(parameter_parachutes, "parachutes_drogue_", constants, variations)

    check_required(parameter_parachutes, ["trigger", "sampling_rate"], "parachutes_main")

    if has_drogue:
        check_required(parameter_parachutes, ["trigger", "sampling_rate"], "parachutes_drogue")
    
    if DEBUG: 
        print(parameter_parachutes)
        
    parachute_sets = []

    for parachute_values in generate_combinations(parameter_parachutes, constants, variations):
        parachute_set = {}
        main_parachute_options = {
            "name": "main",
            "cd_s": get_parachute_cd_s(parachute_values, "parachutes_main"),
            "trigger": parachute_values["parachutes_main_trigger"],             # m
            "sampling_rate": parachute_values["parachutes_main_sampling_rate"], # hz
        }

        if "parachutes_main_radius" in parachute_values:
            main_parachute_options["radius"] = parachute_values["parachutes_main_radius"]

        if "parachutes_main_cd" in parachute_values:
            main_parachute_options["drag_coefficient"] = parachute_values["parachutes_main_cd"]

        if "parachutes_main_lag" in parachute_values:
            main_parachute_options["lag"] = parachute_values["parachutes_main_lag"]                      # s

        if "parachutes_main_noise" in parachute_values:
            main_parachute_options["noise"] = parachute_values["parachutes_main_noise"]                 # (pa, pa, pa)

        main_parachute = Parachute(**main_parachute_options)
        attach_meta(main_parachute, {key: parachute_values[key] for key in variations if key in parachute_values})
        parachute_set[0] = main_parachute

        if has_drogue:
            drogue_parachute_options = {
                "name": "drogue",
                "cd_s": get_parachute_cd_s(parachute_values, "parachutes_drogue"),
                "trigger": parachute_values["parachutes_drogue_trigger"],             # m
                "sampling_rate": parachute_values["parachutes_drogue_sampling_rate"], # hz
            }

            if "parachutes_drogue_radius" in parachute_values:
                drogue_parachute_options["radius"] = parachute_values["parachutes_drogue_radius"]

            if "parachutes_drogue_cd" in parachute_values:
                drogue_parachute_options["drag_coefficient"] = parachute_values["parachutes_drogue_cd"]

            if "parachutes_drogue_lag" in parachute_values:
                drogue_parachute_options["lag"] = parachute_values["parachutes_drogue_lag"]                     # s

            if "parachutes_drogue_noise" in parachute_values:
                drogue_parachute_options["noise"] = parachute_values["parachutes_drogue_noise"]                 # (pa, pa, pa)

            drogue_parachute = Parachute(**drogue_parachute_options)
            attach_meta(drogue_parachute, {key: parachute_values[key] for key in variations if key in parachute_values})
            parachute_set[1] = drogue_parachute

        parachute_sets.append(parachute_set)

        if OUTPUT_LEVEL > 1:
            for parachute in parachute_set.values():
                CustomPlots.plot_parachute_model(parachute)
                
    return register("parachutes", parachute_sets, constants, variations)


# =============================================================================
# Rocket and flight
# =============================================================================

def create_rocket(constants, variations, OUTPUT_LEVEL):
    """
    Create RocketPy rocket objects.

    The config uses explicit ``*_from_tip`` values for measured positions. They are converted to
    RocketPy's bottom-origin coordinate system inside this function.
    """
    print("Creating rocket...")

    constants, variations = create_nosecone(constants, variations)
    constants, variations = create_tailcone(constants, variations)
    constants, variations = create_fins(constants, variations, OUTPUT_LEVEL)
    constants, variations = create_parachutes(constants, variations, OUTPUT_LEVEL)

    parameter_rockets = []

    # defaults = {
    #     "nozzle_position": 0,
    #     "rocket_moment_of_intertia_XY": 0.1,
    #     "rocket_moment_of_intertia_Z": 1,
    # }
    # add_defaults(parameter_rockets, defaults, constants, variations)
    fill_parameters(parameter_rockets, "rocket_", constants, variations)
    fill_parameters(parameter_rockets, "railbuttons_", constants, variations)
    fill_parameters_exact(
        parameter_rockets,
        [
            "motor",
            "nosecone",
            "tailcone",
            "fin_set",
            "parachutes",
            "fins_position",
            "tailcone_length",
            "tailcone_cylindrical_section_length",
        ],
        constants,
        variations,
    )

    check_required(
        parameter_rockets,
        [
            "diameter",
            "length",
            "total_mass_without_motor",
            "total_CG_without_motor_from_tip",
            "moment_of_intertia_XY",
            "moment_of_intertia_Z",
            "power_off_drag",
            "power_on_drag",
        ],
        "rocket",
    )
    check_required(parameter_rockets, ["upper_from_tip", "lower_from_tip"], "railbuttons")
    check_required(parameter_rockets, ["motor", "nosecone", "tailcone", "fin_set", "parachutes"])
    check_required(parameter_rockets, ["position"], "fins")
    check_required(parameter_rockets, ["length", "cylindrical_section_length"], "tailcone")

    rockets = []

    for rocket_values in generate_combinations(parameter_rockets, constants, variations):
        rocket_length_m = millimeters_to_meters(rocket_values["rocket_length"])
        center_of_mass_from_bottom = get_position_from_tip(
            rocket_values["rocket_total_CG_without_motor_from_tip"],
            rocket_length_m,
        )
        upper_railbutton_from_bottom = get_position_from_tip(
            rocket_values["railbuttons_upper_from_tip"],
            rocket_length_m,
        )
        lower_railbutton_from_bottom = get_position_from_tip(
            rocket_values["railbuttons_lower_from_tip"],
            rocket_length_m,
        )
        fin_position_from_bottom = millimeters_to_meters(rocket_values["fins_position"])
        tail_position_from_bottom = millimeters_to_meters(
            rocket_values["tailcone_length"] - rocket_values["tailcone_cylindrical_section_length"]
        )

        rocket = Rocket(
            radius=millimeters_to_meters(rocket_values["rocket_diameter"]) / 2,                      # m
            mass=grams_to_kilograms(rocket_values["rocket_total_mass_without_motor"]),               # kg
            inertia=(
                rocket_values["rocket_moment_of_intertia_XY"],
                rocket_values["rocket_moment_of_intertia_XY"],
                rocket_values["rocket_moment_of_intertia_Z"],
            ),
            power_off_drag=get_project_file(constants, rocket_values["rocket_power_off_drag"]),
            power_on_drag=get_project_file(constants, rocket_values["rocket_power_on_drag"]),
            center_of_mass_without_motor=center_of_mass_from_bottom,                                # m
            coordinate_system_orientation="tail_to_nose",
        )
        rocket.add_motor(rocket_values["motor"], position=0)
        rocket.set_rail_buttons(
            upper_button_position=upper_railbutton_from_bottom,
            lower_button_position=lower_railbutton_from_bottom,
        )
        rocket.add_surfaces(
            surfaces=[rocket_values["nosecone"], rocket_values["fin_set"], rocket_values["tailcone"]],
            positions=[rocket_length_m, fin_position_from_bottom, tail_position_from_bottom],
        )
        rocket.parachutes = list(rocket_values["parachutes"].values())

        attach_meta(rocket, {key: rocket_values[key] for key in variations if key in rocket_values})
        rockets.append(rocket)
        
        if OUTPUT_LEVEL > 1:
            print_one_rocket(rocket, rocket_length_m)
            plot_one_rocket(rocket)

    return register("rocket", rockets, constants, variations)

# =============================================================================
# Flights
# =============================================================================

def create_flight(constants, variations):
    """
    Create scenario flights for every configured environment.

    - Full-flight mode: 
        each scenario (nominal / no_main / ballistic) is simulated from launch to impact.
    - Scan mode (active for VARIATION_KEYS_WITHOUT_FLIGHT_PLOTS and deployable payloads): 
        for each launch configuration, simulates the ascent once and reuses its
        apogee state as the starting point for the descent scenarios, skipping ascent
        re-simulation across the scenario set.
    """
    print("Creating flights...")

    environments = lookup("environments", constants, variations)[0]
    has_drogue = any(key.startswith("parachutes_drogue_") for key in list(constants) + list(variations))
    has_payload = deployable_payload.has_deployable_payload(constants, variations)
    reuse_ascent_flights = any(key in variations for key in VARIATION_KEYS_WITHOUT_FLIGHT_PLOTS) or has_payload

    parameter_flights = []
    
    # defaults = {"flight_terminate_on_apogee": True}
    # add_defaults(parameter_flights, defaults, constants, variations)
    fill_parameters(parameter_flights, "flight_", constants, variations)
    fill_parameters_exact(parameter_flights, "rocket", constants, variations)

    if has_payload:
        fill_parameters_exact(parameter_flights, "payload_mass_total", constants, variations)

    check_required(parameter_flights, ["rail_length", "inclination", "heading"], "flight")

    # One bucket per environment; populated below as combinations are generated.
    flights_by_env = {env_name: [] for env_name in environments}
    ascent_flights_by_env = {env_name: [] for env_name in environments}
    scenarios_per_combo = 3 if has_drogue else 2
    flights_per_combo = scenarios_per_combo + 1 if reuse_ascent_flights else scenarios_per_combo
    total = count_combinations(parameter_flights, variations)
    step = max(1, total // 10)
    # Each combination produces one scenario set per environment, plus an ascent in reuse mode.
    print(f"Amount: {total * flights_per_combo * len(environments)}")

    # create one flight per scenario per environment; reuse ascent flight when configured
    for i, flight_values in enumerate(generate_combinations(parameter_flights, constants, variations), start=1):
        # Build the scenario-specific rocket copies once per combination, then reuse them across envs.
        payload_mass_total = flight_values.get("payload_mass_total", 0)
        scenario_rockets = build_scenario_rockets(flight_values["rocket"], has_drogue, payload_mass_total)
        meta = {key: flight_values[key] for key in variations if key in flight_values}

        print(f"{i / total:.0%}")
        # if i % step == 0 or i == total:
        #     print(f"{i / total:.0%}")
        
        for env_name, environment in environments.items():
            # if i / total >= 0.77:
            #     print(f"env={env_name}, flight_values={flight_values}")
            ascent_flight = None
            scenario_set = {}

            if reuse_ascent_flights:
                # First simulate the full-mass rocket only up to apogee
                ascent_flight = Flight(
                    rocket=flight_values["rocket"],
                    environment=environment,
                    rail_length=flight_values["flight_rail_length"],
                    inclination=flight_values["flight_inclination"],
                    heading=flight_values["flight_heading"],
                    terminate_on_apogee=True,
                    name=f"{env_name}_ascent",
                )
                attach_meta(ascent_flight, meta)
                ascent_flights_by_env[env_name].append(ascent_flight)

            # In reanalysis mode: we only compare to the nominal flight and optionally to a copy of it (matched flight)
            scenarios_for_env = (
                {"nominal": scenario_rockets["nominal"]}
                if env_name.startswith("Reanalysis")
                else scenario_rockets
            )

            for scenario_name, rocket in scenarios_for_env.items():
                # print(f"scenario_rockets={scenario_rockets}")
                flight_options = {
                    "rocket": rocket,
                    "environment": environment,
                    "rail_length": flight_values["flight_rail_length"],
                    "inclination": flight_values["flight_inclination"],
                    "heading": flight_values["flight_heading"],
                    "terminate_on_apogee": False,
                    "name": f"{env_name}_{scenario_name}",
                }

                if ascent_flight is not None:
                    # Continue the scenario from the ascent apogee; payload mass is removed when configured.
                    flight_options["initial_solution"] = ascent_flight

                flight = Flight(**flight_options)
                attach_meta(flight, meta)
                scenario_set[scenario_name] = flight

            flights_by_env[env_name].append(scenario_set)

    constants, variations = register("flights_by_env", flights_by_env, constants, variations)

    if reuse_ascent_flights:
        constants, variations = register("ascent_flights_by_env", ascent_flights_by_env, constants, variations)

    if has_payload:
        constants, variations = deployable_payload.create_payload(constants, variations)
        constants, variations = deployable_payload.create_payload_flight(constants, variations)

    return constants, variations


def build_scenario_rockets(base_rocket, has_drogue, payload_mass_total=0):
    """
    Build the rocket variants for the descent scenarios by deep-copying the base rocket and
    trimming its parachute list. Returns a dict of scenario_name -> rocket.

    When a deployable payload is configured, the scenario rockets represent the post-separation
    rocket, so the configured payload mass is removed before descent is simulated.
    """
    # Each scenario gets its own deep copy so RocketPy can hold scenario-specific parachute lists.
    nominal_rocket = copy.deepcopy(base_rocket)
    ballistic_rocket = copy.deepcopy(base_rocket)
    ballistic_rocket.parachutes = []

    if not has_drogue:
        scenario_rockets = {"nominal": nominal_rocket, "ballistic": ballistic_rocket}
    else:
        no_main_rocket = copy.deepcopy(base_rocket)
        no_main_rocket.parachutes = [parachute for parachute in no_main_rocket.parachutes if parachute.name != "main"]
        scenario_rockets = {"nominal": nominal_rocket, "no_main": no_main_rocket, "ballistic": ballistic_rocket}

    payload_mass_kg = grams_to_kilograms(payload_mass_total)

    if payload_mass_kg > 0:
        for rocket in scenario_rockets.values():
            # remove payload mass from rocket after separation
            rocket.mass -= payload_mass_kg

            if rocket.mass <= 0:
                raise ValueError("payload_mass_total must be smaller than the rocket mass.")

    return scenario_rockets